{% raw %}---
- name: reload monit
  service:
    name: monit
    state: reloaded
  become: true
  become_user: root

- name: restart systemd service
  service:
    name: "{{ project_slug }}.service"
    daemon_reload: yes
    state: restarted
  become: true
  become_user: root{% endraw %}
