{% raw %}---
- name: restart celerybeat service
  service:
    name: "{{ project_slug }}_celerybeat.service"
    daemon_reload: yes
    state: restarted

- name: restart celeryworker service
  service:
    name: "{{ project_slug }}_celeryworker.service"
    daemon_reload: yes
    state: restarted{% endraw %}
